# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Govanhill Voices
email: govanhillvoices@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Govanhill Voices community choir homepage.
  *Photo credit - Audrey Bizouerne.*
baseurl: "" # the subpath of your site, e.g. /blog
url: "govanhillvoices.org.uk" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  govanhillvoices

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Theme-specific settings

minima:
  social_links:
    - { platform: devto,          user_url: "https://dev.to/jekyll" }
    - { platform: facebook,   user_url: "https://www.facebook.com/govanhillvoices" }
    - { platform: instagram,  user_url: "https://www.instagram.com/govanhill_voices" }
    - { platform: youtube,    user_url: "https://www.instagram.com/govanhill_voices" }


